project:
  type: book
  output-dir: docs

book:
  title: "Comparison of travel behaviour of two individuals with different tracking methods"
  subtitle: "PTED Semester Project"
  author:
    - Amelia Heid
    - Christopher Elsener
  date: "2026-06-21"
  downloads: pdf           # adds a PDF download button to the HTML navbar

  chapters:
    - file: index.qmd
      text: "Titelseite"   # sidebar label for the title page
    - chapters/abstract.qmd
    - chapters/introduction.qmd
    - chapters/methods.qmd
    - chapters/results.qmd
    - chapters/discussion.qmd
    - chapters/appendix.qmd
    - chapters/references.qmd
    
  appendices:
    - chapters/appendix.qmd
     # - chapters/proposal2.qmd
    # - 7-anhang-rohdaten.qmd
    # - 8-anhang-statistik.qmd

bibliography: chapters/references/references.bib
lang: en                   # controls automatic text (e.g. "Abgabedatum" vs "Submission date")

institut: "Institute of Natural Resource Sciences"
keywords: "movement analysis, google timeline, GPS, "
confidential: false         # adds a "Vertraulich" notice on the title page
zhaw-cover-image:
  src: figure/cover.png
  max-width: 100%          # optional, constrains the image on the title page
  max-height: 5cm
thesis-type: "Semester Project"
degree-type: "Computational Movement Analysis: Patterns and Trends in Environmental Data"
study-year: "2026"
submission-date: "2026-06-21"
study-direction: "Master of Science in Environment and Natural Resources"
supervisors:
  - title: "Prof. Dr."
    name: "Patrick Laube"
    affiliation: "ZHAW School of Life Sciences and Facility Management, Wädenswil"
  - title: ""
    name: "Nils Ratnaweera"
    affiliation: "ZHAW School of Life Sciences and Facility Management, Wädenswil"


format:
  zhaw-lsfm-html: default
    # format-links: false
      # format-links: false

  zhaw-lsfm-typst: default
  # html:
  #   toc: true
  #   number-sections: true
  #   css:
  #     - _extensions/zhaw-lsfm/zhaw-lsfm/zhaw-html.css
  #   filters:
  #     - _extensions/zhaw-lsfm/zhaw-lsfm/html-labels.lua
  #   template-partials:
  #     - _extensions/zhaw-lsfm/zhaw-lsfm/partials/title-block.html
  #   shortcodes:
  #     - _extensions/zhaw-lsfm/zhaw-lsfm/shortcodes.lua
  #   execute:
  #     warning: false
  #     error: true


