# Appendix

## Usage of AI Models

Complementary, the following AI was used for the listed areas in this project:
@ChatGPT
@Claude

- Paraphrasing text 
- support with coding for more complex processing

The authors of this report take the responsibility for the content. They declare to check the relevance, truthfulness and accuracy of the generative AI systems used and the output they produce and to use it in a reflective, critical and targeted manner. 
They also declare to not upload personal data and other data requiring heightened protection as well as data that is subject to contractual or legal confidentiality. 
@useofAI



## Statement of authorship

The students affirm independent completion of their work without outside help.
The students declare that all printed and electronic sources used in the text and the bibliography are correctly indicated, i.e., that the work does not contain any plagiarism.
In the event of misconduct of any kind, Paragraph 39 and Paragraph 40 of the General Academic Regulations for Bachelor's and Master's degree programmes at the Zurich University of Applied Sciences (dated 29 January 2008) and the provisions of the Disciplinary Measures of the University Regulations shall apply. 
@declarationOwnWork


## Wordcount

<!-- WORDCOUNT-START -->

1'909 words

and

13'837 characters including spaces and references, excluding code listing

<!-- WORDCOUNT-END -->







